### ISSUE TITLE
[Bug] `c-shine__rail` positioning

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit#190]
## Expected Behavior
Shine Rails shouldn't be offset on the `left` by default, the offset should only be handled by the context.

## Attempted Fixes
```css
.c-shine__rail::before,
.c-shine__rail::after {
  left: 0;
}
```

## Context
Currently blocking Hero Shine integration in Toolkit React - https://github.com/sky-uk/toolkit-react/pull/125

---

cc/ @coderas
