### ISSUE TITLE
Extending Gradient Directions

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit#400]
## Expected Behaviour

As a consumer of Toolkit, I would expect to be able to pass my own `$gradient-directions` into the `@include gradient-background()` mixin.

We currently recommend this for using custom gradients in `@include gradient-background()`, I think it could be pretty useful to provide this extra functionality.

e.g.

```scss
$project-gradients: (
  ocean: (
    0%:   #0090D4,
    35%: #232687
  )
);

$project-gradient-directions: (
  diagon-alley: (
    legacy: "top",
    standard: "160deg",
    type: linear,
    reverse: false
  )
);

$gradients: map-merge($gradients, $project-gradients);
$gradient-directions: map-merge($gradient-directions, $project-gradient-directions);

// Usage
.c-foo {
  @include gradient-background("ocean", diagon-alley);
}
```

## Current Behaviour

No such behaviour exists

## Attempted Fixes

Fixed locally by appending `!default;` to the end of the map declaration.

This isn't new and something we do already, but I think it raises other questions on how we safeguard default Toolkit values and prevent them from being overwritten.

## Context

Hoping to use with an internal project
