### ISSUE TITLE
Should we add horizontal and vertical spacing utilities?

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit#423]
## Description

@MrDinsdale re-ignited the idea of utility classes to add horizontal or vertical spacing. He suggested classes such as `u-margin-horizontal-large`, but I think these are a tad long

Perhaps something like:

```css
.u-margin-x {
  margin-left: 20px;
  margin-right: 20px;
}

.u-padding-y {
  padding-top: 20px;
  padding-bottom: 20px;
}
```

## Caveats

* Bloat - this can already be achieved by using two directional utility classes 🤷‍♂️ 
* Vertical rhythm - if used incorrextly, `y-axis` utility classes would disrupt the vertical rhythm
  * In Toolkit, all margins are added to the bottom. A rogue margin added to the top would disrupt this. 

## Context

Enhance Toolkit developer experience
