### ISSUE TITLE
Should we rename the `-all` suffix in our spacing utilities?

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit#424]
## Description

To keep things short and sweet, should we remove the `-all` suffix and rename to:

```css

/* previously `.u-padding-all` */
.u-padding {
  padding-top: 20px;
  padding-right: 20px;
  padding-bottom: 20px;
  padding-left: 20px;
}
```
I think this is much tidier but I'm aware it's a breaking change. What do people think?

## Context

Enhance Toolkit developer experience
